#if !defined(BLOCK_ID_MAPPING)
#define BLOCK_ID_MAPPING
// This file was automatically generated by block_wrangler


bool sway(int id) {
	return id == 1002 || id == 1001 || id == 1013 || id == 1012 || id == 1010 || id == 1011 || id == 1005 || id == 1006 || id == 1004 || id == 1007 || id == 1008 || id == 1009;
}


bool sway_lower(int id) {
	return id == 1002 || id == 1001 || id == 1011 || id == 1013 || id == 1007;
}


bool sway_upper(int id) {
	return id == 1006 || id == 1011 || id == 1012 || id == 1001;
}


bool sway_hanging(int id) {
	return id == 1005 || id == 1010;
}


bool sway_full(int id) {
	return id == 1004 || id == 1009;
}


bool sway_floating(int id) {
	return id == 1008;
}


bool flowers(int id) {
	return id == 1005 || id == 1003 || id == 1006 || id == 1004 || id == 1007;
}


bool crops(int id) {
	return id == 1002 || id == 1001;
}


bool water(int id) {
	return id == 1000;
}


#endif // BLOCK_ID_MAPPING